apps/accounts/urls.py
from django.urls import path
from .views import Login_user,Register_user,logout_user
app_name = "accounts"
urlpatterns = [
    path("login/",Login_user.as_view(),name="login"),
    path('register/',Register_user.as_view(),name="register"),
    path('logout/',logout_user,name="logout")
]

apps/password/urls.py
from django.urls import  path
from .views import (CreatePassword,
                    PasswordDetail, PasswordUpdate,
                    PasswordDelete, PasswordList)

app_name = "password"

urlpatterns =[
    path("", PasswordList.as_view(), name="home"),
    path('create/',CreatePassword.as_view(),name="add_password"),
    path('detail/<int:id>/<str:token>/',PasswordDetail.as_view(),name="detail"),
    path('update/<int:id>/<str:token>/',PasswordUpdate.as_view(),name="update"),
    path('delete/<int:id>/<str:token>/',PasswordDelete.as_view(),name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.password.urls")),

    path('accounts/', include('allauth.urls')),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from .managers import UserManager

class User(AbstractUser):
    nick_name = models.CharField(max_length=120, unique=True)
    email = models.EmailField(unique=True, max_length=80)
    token = models.CharField(max_length=15, unique=True)
    username = None

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["nick_name"]

    objects = UserManager()

    def __str__(self):
        return self.email

apps/password/models.py
from django.db import models
from accounts.models import User


class Password(models.Model):
    title = models.CharField(max_length=120)
    password = models.CharField(max_length=120)
    owner = models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE, related_name="password_owner")
    token = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return  self.title

apps/accounts/forms.py
from django import  forms
from  django.contrib.auth.forms import UserCreationForm

import random

from accounts.models import User

class RegisterForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('nick_name', 'email', 'password')
        help_texts = {
            'password' : None,
        }

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.token = random.randint(1, 99999999999999)

        if commit:
            user.save()

        return user

apps/password/forms.py
from django import  forms
from password.models import  Password
class PassWordForm(forms.ModelForm):
    class Meta:
        model = Password
        fields = ("title", "password", "owner", "token")
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your title'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter your password'}),
        }

apps/password/views.py
from django.shortcuts import redirect, get_object_or_404

from django.views.generic import (
	ListView, FormView, UpdateView,
	DetailView, DeleteView
)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid 

from .forms import PassWordForm
from .encryption import decode, encode
from .mixins import EditAccess
from password.models import Password

# Create your views here.

class PasswordList(LoginRequiredMixin,ListView):
	'''
		Main Page
	'''
	template_name = "password/list_password.html"
	def get_queryset(self):
		return  Password.objects.filter(owner=self.request.user)

class CreatePassword(LoginRequiredMixin, FormView):
	'''
		Save a password and encode it to base64
	'''
	template_name = template_name = "password/add_password.html"
	form_class = PassWordForm

	def form_valid(self,form):
		form = form.save(commit=False)
		form.password = encode(form.password)
		form.token =  uuid.uuid4().hex.upper()[0:15]
		form.owner = self.request.user
		form.save()
		return redirect('password:home')

class PasswordDetail(LoginRequiredMixin, EditAccess, DetailView):
	'''
		Detail page for password
	'''
	template_name = "password/detail_password.html"

	def get_object(self):
		token = self.kwargs.get('token')
		id = self.kwargs.get("id")
		object = get_object_or_404(Password, id= id, token= token)
		global password_context
		password_context = decode(object.password)
		return object

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['password'] = password_context.decode("utf-8")
		return context


class PasswordUpdate(LoginRequiredMixin,UpdateView,EditAccess):
	template_name =  "password/update_password.html"
	model =  Password
	fields = ["title","password"]
	pk_url_kwarg = 'token'

	def get_initial(self):
		return {"password":""}

	def get_object(self):
		return get_object_or_404(Password, id= self.kwargs["id"], token= self.kwargs["token"])

	def form_valid(self,form):
		owner_form = form.save(commit=False)
		owner_form.password = (__import__('base64').b64encode(owner_form.password.encode()))
		owner_form.save()
		return redirect('password:home')

class PasswordDelete(LoginRequiredMixin, EditAccess, DeleteView):
	template_name = 'password/delete_password.html'
	pk_url_kwarg = 'token'
	model = Password
	success_url = reverse_lazy('password:home')

	def get_object(self):
		return get_object_or_404(Password, id= self.kwargs["id"], token= self.kwargs["token"])

apps/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'base/navbar.html' %}
    <br>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
     {%block body%}
    {%endblock%}
    </div>

</body>
</html>

apps/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">PM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <a class="nav-link" href="{%url 'password:add_password'%}">Add password</a>
          <a class="nav-link" href="{%url 'account_logout'%}">Logout</a>
          <a class="nav-link" href="https://github.com/Ml06py/django-password-manager">Github</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account_signup'%}">Register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
      {% endif %}

      </ul>
    </div>
  </div>
</nav>

apps/templates/password/add_password.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add password</title>
</head>
<body>
    {%block body%}
        <form method="POST" action="">
        {%csrf_token%}
        <table class="table table-striped table-hover table-bordered">
        <td>
                  <div class="card-body">
                    <h5 class="card-title">{{form.title|as_crispy_field}}</h5>
                    <hr>
                    <div class="mb-3">
                        <li>{{form.password|as_crispy_field}}</li><hr>
                    </div>
                    <br>
                    <button  class="btn btn-outline-success btn-sm">Save</button>
                </div>
        </td>
    </table>
    </form>
    {%endblock%}
</form>
</body>
</html>

apps/templates/password/delete_password.html
{% extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete password</title>
</head>
<body>
{%block body%}
    <form method="post">{% csrf_token %}
        <table class="table table-striped table-hover table-bordered">
        <td>
                  <div class="card-body">
                    <h5 class="card-title">Are you sure about it???</h5>
                    <hr>
                    <div class="mb-3">
                    </div>
                    <br>
                    <input type="submit" value="Delete" class="btn btn-danger">
                </div>
        </td>
    </table>
    </form>
{%endblock%}
</body>
</html>

apps/templates/password/detail_password.html
{%extends 'base/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Detail</title>
</head>
<body>
{%block body%}
    <table class="table table-striped table-hover table-bordered">
        <td>
                  <div class="card-body">
                    <h5 class="card-title">Title: {{object.title}}</h5>
                    <hr>
                    <div class="mb-3">
                        <li id="password">Password: {{password}}</li><hr>
                    </div>
                    <br>
                    <a href="{% url 'password:update' object.id object.token %}" class="btn btn-outline-secondary btn-sm">Update</a>
				    <a href="{% url 'password:delete' object.id object.token %}" class="btn btn-outline-danger btn-sm">Delete</a>
                </div>
        </td>
    </table>
{%endblock%}

</body>
</html>

apps/templates/password/list_password.html
{% extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All passwords</title>
</head>
<body>
{%block body%}
    <table class="table table-striped table-hover table-bordered">
        {% for password in object_list %}
            <tr>
                <td>
                    <a href="{% url 'password:detail' password.id password.token %}">{{password}}</a>
                </td>
                <td align="right">
                    <a href="{% url 'password:update' password.id password.token %}" class="btn btn-outline-secondary btn-sm">Update</a>
                    <a href="{% url 'password:delete' password.id password.token %}" class="btn btn-outline-danger btn-sm">Delete</a>
                </td>
            </tr>
        {%empty%}
            <h3>Password list is empty</h3>
            <a href="{% url 'password:add_password' %}" class="btn btn-success">Add one</a>
        {% endfor %}
    </table>
{%endblock%}
</body>
</html>

apps/templates/password/update_password.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
{%block body%}
    <form method="POST" action="">
        {%csrf_token%}
        <table class="table table-striped table-hover table-bordered">
        <td>
                  <div class="card-body">
                    <h5 class="card-title">{{form.title|as_crispy_field}}</h5>
                    <hr>
                    <div class="mb-3">
                        <li>{{form.password|as_crispy_field}}</li><hr>
                    </div>
                    <br>
                    <button  class="btn btn-outline-success btn-sm">Save</button>
                </div>
        </td>
    </table>
    </form>
{%endblock%}
</body>
</html>